# Generated by Django 5.2.4 on 2026-09-26 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=32)),
                ('license_type', models.CharField(max_length=8)),
                ('license_expire_date', models.DateField(null=True)),
                ('hire_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=24)),
                ('driving_hours', models.IntegerField(default=0)),
                ('violation_count', models.IntegerField(default=0)),
                ('daily_drive_limit_minutes', models.IntegerField(default=480, verbose_name='每日驾驶上限（分钟）')),
                ('min_rest_minutes', models.IntegerField(default=60, verbose_name='相邻任务最短休息（分钟）')),
                ('night_rest_minutes', models.IntegerField(default=480, verbose_name='夜间最短连续休息（分钟，22:00-次日06:00）')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=32)),
                ('vehicle_type', models.CharField(max_length=32)),
                ('brand_model', models.CharField(max_length=80)),
                ('purchase_date', models.DateField(null=True)),
                ('insurance_expire_date', models.DateField(null=True)),
                ('inspection_expire_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=24)),
                ('mileage', models.IntegerField(default=0)),
                ('tank_capacity', models.FloatField(default=0)),
                ('fuel_consumption', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=24)),
                ('items', models.JSONField(default=list)),
                ('cost', models.FloatField(default=0)),
                ('vendor', models.CharField(max_length=120)),
                ('date', models.DateField(null=True)),
                ('next_mileage', models.IntegerField(default=0)),
                ('next_date', models.DateField(null=True)),
                ('status', models.CharField(max_length=24)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('liters', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('mileage', models.IntegerField(default=0)),
                ('station', models.CharField(max_length=120)),
                ('payment_method', models.CharField(max_length=24)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=40)),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('plan_depart_at', models.DateTimeField(null=True)),
                ('plan_arrive_at', models.DateTimeField(null=True)),
                ('actual_depart_at', models.DateTimeField(null=True)),
                ('actual_arrive_at', models.DateTimeField(null=True)),
                ('cargo', models.CharField(max_length=160)),
                ('weight', models.FloatField(default=0)),
                ('freight', models.FloatField(default=0)),
                ('status', models.CharField(max_length=24)),
                ('creator_id', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_app.driver')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_app.vehicle')),
            ],
        ),
    ]
